"""Alter table Todos

Revision ID: b551a0370bf5
Revises: a102c07f9916
Create Date: 2023-10-27 22:56:54.694970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b551a0370bf5'
down_revision = 'a102c07f9916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_access', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_refresh', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('token_refresh')
        batch_op.drop_column('token_access')

    # ### end Alembic commands ###
